### ISSUE TITLE
登录无法验证码图片无法加载

### ISSUE THREAD

**Issue by 1569462270** [gz-yami/mall4cloud#20]
![image](https://user-images.githubusercontent.com/84381016/235102105-f7c0eb4a-f38e-4321-8043-deb567a0ab74.png)

**Comment by newcomer3** [comment]
你是傻逼吗

**Comment by newcomer3** [comment]
傻鸟白志豪

**Comment by 1569462270** [comment]
> 你是傻逼吗

废物东西，你在狗叫什么？

**Comment by leoba1** [comment]
> 你是傻逼吗

你又是什么🐕吧

**Comment by liuweihong** [comment]
> > 你是傻逼吗
> 
> 你又是什么🐕吧

一群傻逼

**Comment by leoba1** [comment]
> > > 你是傻逼吗
> > 
> > 
> > 你又是什么🐕吧
> 
> 一群傻逼

宁又是什么傻逼

**Comment by liuweihong** [comment]
傻逼在问我么？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月19日(周五) 下午3:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gz-yami/mall4cloud] 登录无法验证码图片无法加载 (Issue #20)




    
你是傻逼吗
  
你又是什么🐕吧
  
一群傻逼
  
宁又是什么傻逼

**Comment by ss1068** [comment]
![image](https://github.com/gz-yami/mall4cloud/assets/93534701/3b55bbe5-f9e7-4000-b2f2-a8d1e8bb75cd)
这个地方地址需要填写你本地的地址(就是你后台服务的地址)

**Comment by WangH26** [comment]
您好，您的邮件我已收到，谢谢您~

**Comment by gz-yami** [comment]
评论还有不友好信息，关闭
